env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
# rules: {}
rules:
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version