name: lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: preparing for lint
        run: npm ci #Without this linter will not work
      
      - name: runnig linter
        run: make lint
