name: tests
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: preparing
        run: npm i --save-dev jest
        
      - name: preparing 2
        run: npx ci
        
      - name: runnig tests
        run: NODE_OPTIONS=--experimental-vm-modules npx jest
