name: tests
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: preparing
        run: npm i --save-dev jest
        
      - name: runnig tests
        run: npx jest
