name: tests
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: preparing
        run: npm ci
        
      - name: runnig tests
        run: NODE_OPTIONS=--experimental-vm-modules npx jest
